site_name: "TNFR × LFS Toolkit"
site_description: "Operational documentation for the TNFR × LFS telemetry and recommender toolkit."
site_url: ""

theme:
  name: mkdocs

nav:
  - Documentation index: index.md
  - Getting started:
      - Beginner quickstart: tutorials.md
      - Examples gallery: examples.md
      - Advanced workflows: advanced_workflows.md
      - Command line interface: cli.md
  - Reference:
      - How the API is organised: api_reference.md
      - API Index: reference/autoapi/index.md
      - Operator mapping: operators_mapping.md
      - Calibration workflow: calibration.md
      - Design manual: DESIGN.md
      - Development workflow: DEVELOPMENT.md
      - Release process: release_process.md
      - Setup equivalences: setup_equivalences.md
      - Setup plan workflow: setup_plan.md
      - Preset workflow: presets.md
      - Brake thermal proxy: brake_thermal_proxy.md
      - Plugin architecture: plugins.md
  - Glossaries:
      - TNFR glossary: tnfr_translation_glossary.md
      - Spanish translation inventory: spanish_translation_inventory.md

plugins:
  - search
  - mkdocs-autoapi:
      packages:
        - tnfr_lfs
        - tnfr_core
      autoapi_ignore:
        - tnfr_lfs.core*
  - macros:
      modules: []
      module_name: docs/macros
  - mkdocstrings
  - i18n:
      default_language: en
      languages:
        - locale: en
          name: English
          default: true
          build: true
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
