site_name: "TNFR × LFS Toolkit"
site_description: "Operational documentation for the TNFR × LFS telemetry and recommender toolkit."
site_url: ""

theme:
  name: mkdocs

nav:
  - Home: index.md
  - Getting started:
      - Beginner quickstart: tutorials.md
      - Examples gallery: examples.md
      - Advanced workflows: advanced_workflows.md
      - Command line interface: cli.md
  - Reference:
      - API Reference: api_reference.md
      - Design manual: DESIGN.md
      - Development workflow: DEVELOPMENT.md
      - Release process: release_process.md
      - Setup equivalences: setup_equivalences.md
      - Preset workflow: presets.md
      - Brake thermal proxy: brake_thermal_proxy.md
  - Glossaries:
      - TNFR glossary: tnfr_translation_glossary.md
      - Spanish translation inventory: spanish_translation_inventory.md

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en:
          name: English
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
