[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tnfr-lfs"
version = "0.1.0"
description = "Telemetry Normal Force Reconstruction toolkit"
readme = "docs/index.md"
authors = [{ name = "TNFR Team" }]
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "ruff>=0.6.0",
    "mypy>=1.11.0",
    "black>=24.4.0",
]

[project.urls]
Homepage = "https://example.com/tnfr-lfs"

[project.scripts]
"tnfr-lfs" = "tnfr_lfs.cli.tnfr_lfs_cli:main"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra"
testpaths = ["tests"]

[tool.ruff]
target-version = "py39"
line-length = 88
src = ["tnfr_lfs", "tests", "examples", "typing_targets"]

[tool.ruff.lint]
per-file-ignores = {"tests/conftest.py" = ["E402"]}

[tool.black]
line-length = 88
target-version = ["py39"]

[tool.mypy]
python_version = "3.9"
files = ["typing_targets"]
warn_unused_configs = true

[tool.setuptools.package-data]
"tnfr_lfs.data" = ["*.toml"]

[tool.setuptools.data-files]
"tnfr_lfs_pack/data/tracks" = ["data/tracks/*.toml"]
"tnfr_lfs_pack/data/track_profiles" = ["data/track_profiles/*.toml"]
"tnfr_lfs_pack/modifiers/combos" = ["modifiers/combos/*.toml"]
