[logging]
level = "info"
output = "stderr"
format = "json"

[telemetry]
host = "127.0.0.1"
outsim_port = 4123
outgauge_port = 3000
insim_port = 29999

[analyze]
export = "json"

[suggest]
car_model = "FZR"
track = "AS5"

[paths]
output_dir = "out"
pack_root = "."

[limits.delta_nfr]
entry = 0.5
apex = 0.4
exit = 0.6

[cache]
enable_delta_cache = true
nu_f_cache_size = 256

[cache.telemetry]
telemetry_cache_size = 1
