[meta]
id = "fo8__p_fast_long"
car_group = "FO8"
base_profile = "p_fast_long"
description = "Offsets the high aero load on single-seaters for fast circuits."

[scale.weights.entry]
__default__ = 0.94
aero = 1.1
brakes = 0.88

[scale.weights.apex]
__default__ = 1.06
aero = 1.12
anti_roll = 1.05

[scale.weights.exit]
__default__ = 1.1
transmission = 1.08
differential = 1.14

[hints]
slip_ratio_bias = "front"
notes = "Tunes aerodynamic drag and protects the front tyres."
