[meta]
id = "gtr_rwd__p_fast_long"
car_group = "gtr_rwd"
base_profile = "p_fast_long"
description = "Scales exit performance for rear-drive GTs on high-speed circuits."

[scale.weights.entry]
__default__ = 0.96
aero = 1.05
brakes = 0.9

[scale.weights.apex]
__default__ = 1.04
aero = 1.08
springs = 1.02

[scale.weights.exit]
__default__ = 1.12
transmission = 1.15
differential = 1.18

[hints]
slip_ratio_bias = "rear"
notes = "Increases longitudinal stability without sacrificing top speed."
