[steering]
filter = "butterworth_2p"
deadzone_deg = 0.8
rate_limiter_deg_per_s = 260.0
return_gain = 0.72

[tnfr_objective_weights]
balance = 0.30
stability = 0.28
traction = 0.24
confidence = 0.18

[safety_clamps]
delta_nfr = [-0.80, 0.80]
nu_f = [0.18, 0.42]
slip_lat = [-0.55, 0.55]
slip_long = [-0.45, 0.45]

[thermal.brakes]
mode = "auto"
ambient = 25.0
heat_capacity = 18000.0
heating_efficiency = 0.35
convective_coefficient = 0.06
still_air_coefficient = 0.012
minimum_brake_input = 0.02
