[plugins]
auto_discover = true
plugin_dir = "plugins"
max_concurrent = 4

[plugins.telemetry]
enabled = true
entry_point = "tnfr_lfs.plugins.telemetry:TelemetryPlugin"
buffer_seconds = 15
flush_interval = "5s"

[plugins.telemetry.transport]
protocol = "udp"
host = "127.0.0.1"
port = 3000

[plugins.exporter]
enabled = true
entry_point = "tnfr_lfs.plugins.exporter:ExporterPlugin"
targets = ["jsonl", "html"]
flush_on_shutdown = true

[plugins.exporter.jsonl]
path = "out/telemetry.jsonl"
mode = "append"

[plugins.exporter.html]
path = "out/dashboard.html"
template = "docs/templates/dashboard.html"

[plugins.relay]
enabled = false
entry_point = "tnfr_lfs.plugins.relay:RelayPlugin"
channel = "zeromq"
bind = "tcp://127.0.0.1:6000"

[profiles.racing]
max_concurrent = 4
plugins = ["telemetry", "exporter", "relay"]

[profiles.racing.telemetry]
flush_interval = "1s"

[profiles.racing.exporter]
targets = ["jsonl"]
flush_on_shutdown = false

[profiles.racing.relay]
enabled = true
channel = "zeromq"
bind = "tcp://0.0.0.0:6000"

[profiles.practice]
max_concurrent = 2
plugins = ["telemetry", "exporter"]

[profiles.practice.telemetry]
buffer_seconds = 30
flush_interval = "10s"

[profiles.practice.exporter]
targets = ["html"]
path = "out/practice-dashboard.html"
template = "docs/templates/practice.html"
