[meta]
id = "lx__p_technical_short"
car_group = "lx"
base_profile = "p_technical_short"
description = "Strengthens the rear axle on lightweight sports prototypes for linked sections."

[scale.weights.entry]
__default__ = 1.08
brakes = 1.15
suspension = 1.1

[scale.weights.apex]
__default__ = 1.06
anti_roll = 1.12
springs = 1.1

[scale.weights.exit]
__default__ = 1.05
differential = 1.12
transmission = 1.06

[hints]
slip_ratio_bias = "neutral"
notes = "Keeps the signature agility while reducing sudden oversteer."
